config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :trips do
    resources :pickups, shallow: true
  end

  post 'pickups/:id' => 'pickups#update_status', as: "pickups_update"

  # get 'pickups/new'

  # get 'pickups/show'

  # get '/trips/new' => 'trips#new'

  # post '/trips' => 'trips#create'


  # get 'trips/:id' => 'trips#show', as: "trips_show"


  #get 'users/:id' => 'users#show', as: 'user'

  # get 'trips' => 'trips#index', as: "trips_index"


  post 'users/transfer/:id' => 'users#transfer', as: "transfer_credit" 

  get 'users/:id' => "users#show", as: "users_show"

  get 'users/new'

  # for new users signup login logout and destroy
  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/send_sms' => 'twilio#send_sms'

  mount DelayedJobWeb => "/delayed_job"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user 
	has_many :pickups, dependent: :destroy
	validates_presence_of :pickup_time, :total_space

	geocoded_by :start_address
  after_validation :geocode

	def start_address
		self.user.address
	end

	def remaining_space
		self.total_space - self.pickups.sum(:num_bags)
	end

	def driver_name
		self.user.full_name
	end

	def driver_first_name
		self.user.first_name
	end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authorize

  def new
  	@driver = current_user
    @now = Time.current.strftime("%FT%R")
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def index
    @user = current_user
    @trips = Trip.near(@user.address, 2).limit(5)
  end

  def create
    trip = Trip.new(trip_params)
    if trip.save
      flash[:notice] = "New trip scheduled"
      redirect_to users_show_path(trip.user_id)
    else
      flash[:alert] = "No trip created - please try again"
      redirect_to new_trip_path
    end
  end

  def destroy
    trip = Trip.find(params[:id])
    @user = trip.user
    # @pickup_numbers = trip.pickups.map { |pickup| pickup.user.phone_number }
    trip.destroy
    flash[:notice] = "Trip cancelled"
    redirect_to users_show_path(@user)
    # if @pickup_numbers.empty?
    #   redirect_to users_show_path(@user)
    # else
    #   redirect_to send_sms_path(
    #     final_path: users_show_path(@user),
    #     body: "#{@user.full_name} has cancelled their trip and will no longer be picking up your recycling.  Please find another trip.",
    #     sms_numbers: @pickup_numbers
    #   )
    # end
  end

  private
  def trip_params
    params.require(:trip).permit(:total_space, :pickup_time, :user_id)
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/index.html.erb
<% @trips.each do |trip| %>
	<% unless trip.remaining_space == 0 || current_user == trip.user %>
	  <div class="w-75 card border-primary mt-4">
		  <div class="card-block">
		    <div class="card-header bg-success" align="center">
		    	Scheduled for <%= trip.pickup_time.strftime("%B %e, %Y at %l:%M %p") %>
		    </div>
		    <h4 class="card-title mt-3" align="center"><%= trip.driver_name %></h4>
		    <p class="card-text" align="center"><%= trip.start_address %></p>
		    <p class="card-text mb-3" align="center">Space Remaining: <%= trip.remaining_space %></p>
			  <%= button_to "Add Recycling", new_trip_pickup_path(trip.id), method: :get, class: "btn btn-primary col-9 mb-4 btn-lg", align: "center" %>
		  </div>
	  </div>
	<% end %>
<% end %>

app/views/trips/new.html.erb
<%= flash.alert %>

<h3 class="mt-4 mb-4" align="center"><%= @driver.first_name %>'s Trip</h3>

<%= form_for :trip, url: '/trips' do |f| %>
<div class="container">
	<div class="row">
	  <div class="field col-10" align="center">
		  <%= f.label :total_space, "Total Space" %>
		  <%= f.text_field :total_space, class: "form-control mb-4" %>
	  </div>
	 </div>
	  <div class="form-group row">
		<div class="field col-10" align="center">
		  <%= f.label :pickup_time, "Pickup Time" %>
		  <%= f.datetime_field :pickup_time, min: @now, value: @now, class: "form-control mb-4" %>
	    </div>
	   </div>
	  <%= f.hidden_field :user_id, value: @driver.id %>

	<div class="row">
		  <div class="action col-10" align="center">
			  <%= f.submit "Create Trip", class: "form-control btn mb-4 white-btn" %>
		  </div>
  	</div>
</div>

<% end %>

app/views/trips/show.html.erb
<div class="w-75 card border-primary mt-3">
    <div class="card-header text-white bg-success" align="center">
        <h3><%= @trip.user.full_name %>'s Trip</h3>
    </div>
    <div class="card-text mt-3" align="center">
        <p><%= @trip.pickup_time.localtime.strftime("%B %e, %Y at %l:%M %p") %></p>
        <p><%= "Space left for #{@trip.remaining_space} bags" %></p>
    </div>

    <%= button_to "Cancel Trip", trip_path(@trip.id), method: :delete, data: {confirm: 'Deny Pickup?'}, class: "btn col-9 mb-3" %>
</div>

<%= flash.notice %>

<% if @trip.pickups.length > 0 %>
<div class="w-75 card border-primary mt-3">
    <div class="card-header text-white bg-success" align="center">
        <h3>Pickups</h3>
    </div>
      <% @trip.pickups.each do |pickup| %>
        <% unless pickup.completed? %>
          <div class="card-text mt-3" align="center">
      	    <p><%= pickup.recycler_name %></p>
      	    <p><%= pickup.address %></p>
      	    <p>Number of Bags: <%= pickup.num_bags %><p>
      	    <% case pickup.status %>
      	    <% when "created" %>
              <!-- <%= button_to "Accept", pickups_update_path(pickup.id), data: {confirm: 'Accept Pickup?'}, class: "btn col-9 mb-3" %> -->

              <button type="button" class="btn btn-primary col-9 mb-3" data-toggle="modal" data-target="#exampleModal">Accept</button>

              <%=form_tag( pickups_update_path(pickup.id), method: "post") do %>
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel"></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      Accept the trip!
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-primary">Done</button>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>

              <button type="button" class="btn btn-primary col-9 mb-3" data-toggle="modal" data-target="#exampleModal2">Deny</button>

              <%= form_tag( controller: "pickups", action: "destroy", method: "post") do %>
                <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        Deny the trip!
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Done</button>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>


              <!-- <%= button_to "Deny", pickup_path(pickup.id), method: :delete, data: {confirm: 'Deny Pickup?'}, class: "btn col-9 mb-3" %> -->
            <% when "accepted" %>
              <button type="button" class="btn btn-primary col-9 mb-3" data-toggle="modal" data-target="#exampleModal">Complete</button>

              <%= form_tag( pickups_update_path(pickup.id), method: "post") do %>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm That You've Got the Bag!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        All done? Your community thanks you, but more importantly, the Earth does!
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Done</button>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% when "picked_up" %>
              Pending
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>