config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :trips do
    resources :pickups, shallow: true
  end

  post 'pickups/:id' => 'pickups#update_status', as: "pickups_update"

  # get 'pickups/new'

  # get 'pickups/show'

  # get '/trips/new' => 'trips#new'

  # post '/trips' => 'trips#create'


  # get 'trips/:id' => 'trips#show', as: "trips_show"


  #get 'users/:id' => 'users#show', as: 'user'

  # get 'trips' => 'trips#index', as: "trips_index"


  post 'users/transfer/:id' => 'users#transfer', as: "transfer_credit" 

  get 'users/:id' => "users#show", as: "users_show"

  get 'users/new'

  # for new users signup login logout and destroy
  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/send_sms' => 'twilio#send_sms'

  mount DelayedJobWeb => "/delayed_job"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips, dependent: :destroy
  has_many :recycling_pickups, class_name: 'Pickup', dependent: :destroy
  has_many :driver_pickups, through: :trips, source: :pickups
  has_attached_file :avatar, styles: { medium: "300x300>" , thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :avatar, presence: true, content_type: { content_type: /\Aimage\/.*\z/ }
  has_secure_password
  validates_presence_of :first_name, :last_name, :email, :phone_number
  validates_presence_of :street, :city, :state, :country, :zip_code
  validates_uniqueness_of :email
  geocoded_by :address
  after_validation :geocode
  validates :phone_number, phone: true


  def full_name
  	"#{self.first_name} #{self.last_name}"
  end

  def address
    [street, city, state, zip_code, country].compact.join(', ')
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authorize, :except => [:create, :new]

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = user.id
  		redirect_to '/', notice: 'Account created successfully'
  	else
      flash[:error] = 'An error occured!'
  		render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def authorize
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, :except => [:create, :new]

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to "/users/#{@user.id}"
    end
    # @user = current_user
    @trips = @user.trips
  end

  def new
  end

  def create
  	@user = User.new(user_params)
    @user.credit_count = 1
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to '/', notice: "Welcome, #{@user.first_name}!"
  	else
      flash[:error] = 'An error occured!'
  		render 'new'
  	end
  end

  def transfer
      @user = current_user
      @pickup = Pickup.find(params[:id])
      @driver = @pickup.trip.user
      @num_bags = @pickup.num_bags
      @user.credit_count -= @num_bags
      @driver.credit_count += @num_bags
      @user.save
      @driver.save
      @pickup.destroy
      redirect_to users_show_path(@user)
  end

  private
  	def user_params
  		params.require(:user).permit(
        :first_name,
        :last_name,
        :avatar,
        :phone_number,
        :email,
        :password,
        :password_confirmation,
        :street,
        :city,
        :state,
        :zip_code,
        :country
        )
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<!-- <h1 class="mb-4" align="center"><strong>Signup</strong></h1> -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAteD6sbsGcV1f8mrbvbYUaJPnUyWxwHrk"></script>

<%= form_for :user, url: '/users' do |f| %>

  <div class="field mt-4" align="center">
	  <%= f.label :first_name, "First Name" %>
	  <%= f.text_field :first_name, class: "form-control col-8 mb-4" %>
  </div>

	<div class="field" align="center">
	  <%= f.label :last_name, "Last Name" %>
	  <%= f.text_field :last_name, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
	  <%= f.label :email %>
		<%= f.text_field :email, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
    <%= f.label :phone_number, "Phone Number" %>
    <%= f.text_field :phone_number, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
	  <%= f.label :password %>
	  <%= f.password_field :password, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
	  <%= f.label :password_confirmation, "Password Confirmation" %>
	  <%= f.password_field :password_confirmation, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
    <%= f.label :street %>
    <%= f.text_field :street, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control col-8 mb-4" %>
  </div>
  
  <div class="field" align="center">
    <%= f.label :zip_code, "Zip/Postal Code" %>
    <%= f.text_field :zip_code, class: "form-control col-8 mb-4" %>
  </div>

  <div class="field" align="center">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control col-8 mb-4" %>
  </div>

  <div class="mt-4" align="center">
    <%= recaptcha_tags %>
  </div>

  <div class="field" align="center">
  	<%= f.label :avatar, "Profile Picture" %>
	  <%= f.file_field :avatar, class: "form-control col-8 mb-4 btn-light" %>
  </div>

  <div class="action mb-4" align="center">
	  <%= f.submit "Submit", class: "btn col-8" %>
  </div>

<% end %>

app/views/users/show.html.erb
<%= flash.notice %>

<h2 class="mt-4" align="center">Hello, <%= @user.first_name %>!</h2>
<div class="container-fluid">
  <div class="avatar">
    <%= image_tag(@user.avatar.url(:thumb)) %>
  </div>


  <h4 class="mt-4" align="center">Credit count: <%= @user.credit_count%></h4>

  <% if @user.trips.length > 0 %>
    <h3 class="mt-4 mb-4 title-area" align="center">Trips</h3>
  	<% @user.trips.each do |trip| %>
  		<div class="card w-75 border-info text-center">
  			<div class="card-block trip" align="center">
  				<!-- <div class="col col-10" align="center"> -->
  				    <p class="mt-4 col-12 card-text" id="text"><%= trip.pickup_time.strftime("%B %e, %Y at %l:%M %p") %></p>
  				<!-- </div> -->
  				<!-- <div class="col col-10" align="center"> -->
  					<p class="mt-5 col-9 card-text" id="text">Pickups: <%= trip.pickups.count %></p>
  				<!-- </div> -->
  				<!-- <div class="col col-10" align="center"> -->
  					<%= button_to "View Trip", trip_path(trip.id), method: :get, class:"btn mt-4 mb-4 col-9 white-btn", id:"button"%>
  				<!-- </div> -->
  			</div>
  		</div>
  	<% end %>
  <% end %>

  <% if @user.recycling_pickups.length > 0 %>
  	<h3 class="mt-4 mb-4 bgcolor" align="center">Pickups</h3>
  	<% @user.recycling_pickups.each do |pickup| %>
  		<div class="card w-75 border-info text-center">
  			<div class="card-block trip" align="center">
  				<div class="col col-10" align="center">
            <p class="mt-4 col-12 card-text" id="text"><%= pickup.driver_name %></p>
          </div>

          <div class="col col-10" align="center">
            <p class="mt-4 col-12 card-text" id="text">Number of Bags: <%= pickup.num_bags %></p>
          </div>
          <% case pickup.status %>
            <%when "created" %>
            <div class="mb-4 mt-3">
              Status: Waiting for acceptance
            </div>
            <%when "accepted"%>
            <div>
              Status: Accepted! Put your bag out for pickup.
            </div>
            <%when "picked_up"%>
            <div class="mb-4 mt-3">
              Status: Your bag has been picked up, please confirm!
            </div>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Complete
              </button>

              <%= form_tag( transfer_credit_path(pickup.id), method: "post") do %>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm that the bag has been picked up!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        All done? Your community thanks you, but more importantly, the Earth does!
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Done</button>
                      </div>
                    </div>
                  </div>
                </div>
              <%end%>
          <%end%>
  	   </div>
     </div>
  <%end%>
  <% end %>
</div>